version: "3"
services:
  mongo-container:
    image: mongo:latest
  banter-board-backend-docker:
    image: banter-board-backend-docker:latest
    ports:
      - 8080:8080
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo-container
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=banter
    links:
      - mongo-container
